 $(function(){
               
            $("#form1").validate({
                submitHandler(form){
                    $.ajax({
                        type:"post",
                        url:"php/zhu_che.php",
                        data:$(form).serialize(),
                        dataType:"json",
                        //"uname=dongdong&upwd1=123456&..."
                        success:function(data){
                            alert(data.msg);
                            form.reset();
                        }
                    })
                },
                rules:{
					uname:{
						required:true,
						minlength:5,
						remote:"php/vali.php"
					},
					upwd1:{
						required:true,
						minlength:8,
						maxlength:12,
						digits:true
					},
					upwd2:{
						required:true,
						equalTo:"#upwd1"
					},
					agree:"required"
				}, 
				messages:{
					uname:{
						required:"用户名不能为空！",
						remote:"用户名已被占用"
					},
					upwd1:{required:"密码不能为空！"},
					upwd2:{
						required:"确认密码不能为空！",
						equalTo:"两次密码输入不一样"
					},
					agree:{required:"必须同意网站规则"}
				}
            })
 })